#!/bin/bash
opencv_traincascade -data classifiers -vec close_samples.vec -bg negatives.txt\
  -numStages 1 -minHitRate 0.999 -maxFalseAlarmRate 0.5 -numPos 160\
  -numNeg 489 -w 40 -h 40 -mode ALL -precalcValBufSize 1024\
  -precalcIdxBufSize 1024